baseURL: https://david.gyttja.com
languageCode: en-us
title: david
theme: etch
disableHugoGeneratorInject: true
enableEmoji: false
description: Basic personal site theme styled with minimal tachyons, syntax
  highlighting, and blog series configuration.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: native
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  highlight:
    light: friendly
    dark: native
  copyright: © 2010-2022

menu:
  main:
  # - identifier: posts
  #   name: posts
  #   url: /
  #   weight: -120
  - identifier: categories
    name: categories
    url: /categories/
    weight: -110
  - identifier: about
    name: about
    url: /about/
    weight: -100
  - identifier: qhn
    name: qhn
    url: https://quiethn.gyttja.com/
    weight: -90
  social:
  - identifier: mastodon
    name: Mastodon
    url: https://hachyderm.io/@dfuchslin
    weight: -200
  - identifier: github
    name: GitHub
    url: https://github.com/dfuchslin
    weight: -190
  - identifier: instagram
    name: Instagram
    url: https://www.instagram.com/dfuchslin/
    weight: -180
  - identifier: twitter
    name: Twitter
    url: https://twitter.com/dfuchslin
    weight: -170


Permalinks:
  post: post/:slug
